"""Utility functions for Fractal Bitcoin."""

from ..utils.encoding import (
    hex_to_bytes,
    bytes_to_hex,
    int_to_bytes,
    bytes_to_int,
    encode_varint,
    decode_varint,
    double_sha256,
    hash160,
    hash256,
    encode_base58,
    decode_base58,
    encode_base58_check,
    decode_base58_check,
    encode_bech32,
    decode_bech32,
    decode_address,
    encode_address,
    serialize_script,
    deserialize_script,
    tagged_hash,
    lift_x
)

from ..utils.validation import (
    is_valid_address,
    validate_address,
    is_valid_txid,
    validate_txid,
    is_valid_block_hash,
    validate_block_hash,
    is_valid_amount,
    validate_amount,
    to_satoshi,
    to_btc,
    is_valid_private_key,
    validate_private_key,
    is_valid_public_key,
    validate_public_key,
    is_valid_script,
    validate_script,
    is_dust_amount,
)

__all__ = [
    # Encoding
    "hex_to_bytes",
    "bytes_to_hex",
    "int_to_bytes",
    "bytes_to_int",
    "encode_varint",
    "decode_varint",
    "double_sha256",
    "hash160",
    "hash256",
    "encode_base58",
    "decode_base58",
    "encode_base58_check",
    "decode_base58_check",
    "encode_bech32",
    "decode_bech32",
    "decode_address",
    "encode_address",
    "serialize_script",
    "deserialize_script",
    "tagged_hash",
    "lift_x",
    
    # Validation
    "is_valid_address",
    "validate_address",
    "is_valid_txid",
    "validate_txid",
    "is_valid_block_hash",
    "validate_block_hash",
    "is_valid_amount",
    "validate_amount",
    "to_satoshi",
    "to_btc",
    "is_valid_private_key",
    "validate_private_key",
    "is_valid_public_key",
    "validate_public_key",
    "is_valid_script",
    "validate_script",
    "is_dust_amount",
]